azure:
  storage:
    accountName: ${storageAccountName}
    key: ${storageAccountKey}
    baseUrl: https://%s.blob.core.windows.net

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true