base-microservice:
  nameOverride: azure-blob-management-service
  image:
    repository: abhi2495/azure-blob-management-service
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 500Mi
  probe:
    initialDelaySeconds: 120