name: Master Commit Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      run: ./gradlew clean build -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
  sonar-scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run sonar build
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        run: ./gradlew sonarqube -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} -Dsonar.organization=abhi-dummy-org -Dsonar.coverage.jacoco.xmlReportPaths=build/jacoco-report.xml
  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Jar with Gradle
        env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
        run: ./gradlew clean bootJar -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }} #The owner and repository name. For example, abhi2495/Hello-World
          tags: latest
  deploy-to-dev:
    needs: [push-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Kubernetes context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'rg-jda-lso-dev-eus-02'
          cluster-name: 'aks-jda-lso-dev-eus-02'
      - name: Install Helm
        uses: Azure/setup-helm@v1
      - name: Add azure to helm repo list
        run: helm repo add azure https://helmchartsrepo.blob.core.windows.net/helm/\?se\=2021-05-31\&sp\=rl\&sv\=2018-11-09\&sr\=c\&sig\=21czaRxY8hmYcG6UK38KtRvB1nl%2BhI69WML3oCRShbg%3D
      - name: Fetch helm dependencies
        run: helm dependency update ./charts/azure-blob-management-service
      - name: Run helm upgrade
        run: helm upgrade --install dev ./charts/azure-blob-management-service
      - name: Run kubectl check
        run: kubectl version
    

