name: Master Commit Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      run: ./gradlew clean build -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Jar with Gradle
        env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
        run: ./gradlew clean bootJar -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }} #The owner and repository name. For example, abhi2495/Hello-World
          tags: latest

