name: Master Commit Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Print branch name
      run: echo ${{ github.ref }}
    - name: Build with Gradle
      env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      run: ./gradlew clean build -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: build/libs/*.jar
    - name: Upload Jacoco reports
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-reports
        path: build/jacocoHtml/
  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: app-jar
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }} #The owner and repository name. For example, abhi2495/Hello-World
          tags: latest

