name: Pull Request To Master Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      run: ./gradlew clean build -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
