name: Pull Request To Master Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 #Disabling shallow clone
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle build with Sonar Scan
      env:
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
      run: ./gradlew clean build sonarqube -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} -Dsonar.pullrequest.base=master -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} -Dsonar.organization=abhi-dummy-org -Dsonar.coverage.jacoco.xmlReportPaths=build/jacoco-report.xml
