name: PR Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: PR branch name
      run: echo ${{ github.event.pull_request.head.ref }}
    - name: Build with Gradle
      env:
          storageAccountName: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          storageAccountKey: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      run: ./gradlew clean build -P storageAccountName=$storageAccountName -P storageAccountKey=$storageAccountKey
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
